name = "csv-do"
account_id = "b6641681fe423910342b9ffa1364c76d"
route = { pattern = "*/*", zone_id = "dcd5d34c088be24bc9e73b4ade737291" }
main = "worker.js"
usage_model = "unbound"
compatibility_date = "2022-08-23"

services = [
  { binding = "CTX", service = "ctx-do", environment = "production" },
  { binding = "CSV", service = "csv-do", environment = "production" },
]
